---
# defaults file for openwrt

openwrt_platform: ramips/mt7621
# openwrt_device: xiaomi_mi-router-4
openwrt_device: xiaomi_redmi-router-ac2100
# openwrt_version: SNAPSHOT
openwrt_version: 22.03.0-rc4

# OpenWrt Firmware Selector: Development Snapshots, Stable Release
openwrt_firmware_url: https://firmware-selector.openwrt.org
openwrt_firmware_version_data: "{{ openwrt_firmware_url }}/data/{{ openwrt_version }}/overview.json"
openwrt_firmware_device_data: "{{ openwrt_firmware_url }}/data/{{ openwrt_version }}/{{ openwrt_platform }}/{{ openwrt_device }}.json"

# OpenWrt Downloads: Upcoming Stable Release, Stable Release
openwrt_downloads_url: https://downloads.openwrt.org
openwrt_downloads_sha256sums: "{{ openwrt_downloads_url }}/releases/{{ openwrt_version }}/targets/{{ openwrt_platform }}/sha256sums"
openwrt_downloads_sysupgrade: "{{ openwrt_downloads_url }}/releases/{{ openwrt_version }}/targets/{{ openwrt_platform }}/openwrt-{{ openwrt_version }}-{{ openwrt_platform | regex_replace('/', '-') }}-{{ openwrt_device }}-squashfs-sysupgrade.bin"

openwrt_opkg:
  - irqbalance
  - speedtest-netperf

openwrt_opkg_adblock:
  - adblock
  - luci-app-adblock
  - curl

openwrt_opkg_prometheus_node_exporter_lua:
  - prometheus-node-exporter-lua
  - prometheus-node-exporter-lua-nat_traffic
  - prometheus-node-exporter-lua-netstat
  - prometheus-node-exporter-lua-openwrt
  - prometheus-node-exporter-lua-textfile
  - prometheus-node-exporter-lua-wifi
  - prometheus-node-exporter-lua-wifi_stations

openwrt_opkg_zsh:
  - zsh
  - ca-certificates
  - git-http
  # - curl
