---
# defaults file for openwrt

openwrt_platform: ramips/mt7621
# openwrt_device: xiaomi_mi-router-4
openwrt_device: xiaomi_redmi-router-ac2100
# openwrt_version: SNAPSHOT
openwrt_version: 21.02.0-rc1

openwrt_downloads_url: https://downloads.openwrt.org
openwrt_downloads_dir: "{{ openwrt_downloads_url }}/{% if openwrt_version == 'SNAPSHOT' %}snapshots{% else %}releases/{{ openwrt_version }}{% endif %}/targets/{{ openwrt_platform }}"
openwrt_sysupgrade_bin: "{{ openwrt_downloads_dir }}/openwrt-{% if openwrt_version == 'SNAPSHOT' %}{% else %}{{ openwrt_version }}-{% endif %}{{ openwrt_platform | replace('/','-') }}-{{ openwrt_device }}-squashfs-sysupgrade.bin"
openwrt_sha256sums: "{{ openwrt_downloads_dir }}/sha256sums"

openwrt_opkg_adblock:
  - adblock
  - luci-app-adblock
  - curl

openwrt_opkg_prometheus_node_exporter_lua:
  - prometheus-node-exporter-lua
  - prometheus-node-exporter-lua-nat_traffic
  - prometheus-node-exporter-lua-netstat
  - prometheus-node-exporter-lua-openwrt
  - prometheus-node-exporter-lua-textfile
  - prometheus-node-exporter-lua-wifi
  - prometheus-node-exporter-lua-wifi_stations

openwrt_opkg_zsh:
  - zsh
  - ca-certificates
  - git-http
  # - curl
